name: Dev Pipeline
run-name: ${{ github.actor }} is Running the Github Actions
on: [push, pull_request ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my first job"
        name: " first Job Message"
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my Second Job"
        name: "Print Message"